name: Test
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          version: 11.25.0
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          cache: "pnpm"
          check-latest: true
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: |
          corepack enable
          pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
